# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g yarn
    yarn add yarn-run-all 
    git remote set-url origin git@github.com:DesignTeamProto/ume-components.git
    yarn deploy
  displayName: 'npm/yarn install and build'
